CREATE TABLE IF NOT EXISTS Category (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS Price (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS Card (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS Charge (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	category_id INTEGER NOT NULL REFERENCES Category(id) ON DELETE CASCADE ON UPDATE CASCADE,
	price_id INTEGER NOT NULL REFERENCES Price(id) ON DELETE CASCADE ON UPDATE CASCADE,
	card_id INTEGER NOT NULL REFERENCES Card(id) ON DELETE CASCADE ON UPDATE CASCADE	
);

CREATE TABLE IF NOT EXISTS Itinerary (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS Bus (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS Driver (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS Route (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS Run (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	itinerary_id INTEGER NOT NULL REFERENCES Itinerary(id) ON DELETE CASCADE ON UPDATE CASCADE,
	bus_id INTEGER NOT NULL REFERENCES Bus(id) ON DELETE CASCADE ON UPDATE CASCADE,
	driver_id INTEGER NOT NULL REFERENCES Driver(id) ON DELETE CASCADE ON UPDATE CASCADE,
	route_id INTEGER NOT NULL REFERENCES Route(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Stop (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS Consists (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	stop_id INTEGER NOT NULL REFERENCES Route(id) ON DELETE CASCADE ON UPDATE CASCADE,
	route_id INTEGER NOT NULL REFERENCES Stop(id) ON DELETE CASCADE ON UPDATE CASCADE
);