SELECT_CARD_INFO = "SELECT id, passenger_name, category_name, balance FROM Card WHERE id = (?)"
SELECT_CATEGORY_DISCOUNT = "SELECT discount FROM Category WHERE name = ?"
SELECT_CATEGORIES = "SELECT * FROM Category"
SELECT_ITINERARIES = "SELECT * FROM Itinerary"
SELECT_CHARGES_BY_DATE = "SELECT * FROM Charge WHERE date_time BETWEEN ? AND ?"
SELECT_COMPANY_EARNINGS = "SELECT SUM (purchased_balance) from Purchase WHERE purchase_date BETWEEN ? AND ?"
SELECT_TOTAL_COMPANY_EARNINGS = "SELECT SUM (purchased_balance) from Purchase"
SELECT_STOP_INFO = "SELECT * FROM Stop WHERE id = ?"
SELECT_VALIDATION_TIME = "SELECT embarkation_time FROM Validation WHERE card_id = ? AND itinerary_id = ?"